### 넘파이 배열

1. numpy를 임포트 하라

In [2]:
import numpy as np

2. 0~9를 가지는 배열을 만들고 배열과 type을 출력하라

In [4]:
arr = np.array([i for i in range(0,10)])
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


3. 0~9를 가지는 리스트를 만들고, 각각에 2를 곱하여 새로운 리스트인 answer에 넣어라

In [6]:
arr = [i for i in range(0,10)]
answer = []
for i in arr :
    answer.append(i * 2)
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


4. 0~9를 가지는 numpy 1-dim array를 만들고, 해당 array에 있는 값들에 각각 2를 곱하라

In [9]:
arr = np.array([i for i in range(0,10)])
arr = arr * 2
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


5. 0~9를 가지는 리스트를 만들고, 해당 리스트에 2를 곱하라. 그 후 4.와의 차이를 비교하라.

In [11]:
arr = [i for i in range(0,10)]
arr = arr * 2
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


6. 1,2,3을 가지는 array와 10,20,30을 가지는 array를 각각 만들어라. 그 후 아래를 수행하라.
    - 2 * a + b
    - a == 2
    - (a == 2) & (b > 10)

In [12]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(2 * a + b)
print(a == 2)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True False]


7. 2행 3열의 배열을 만들어라
    - 0 1 2
    - 3 4 5 
    - 이 후, 각각의 열의 갯수와 행의 갯수를 구하라

In [20]:
array = np.array([[0,1,2],[4,5,6]])
print(array)
print("열의 갯수 : " , len(array[0]))
print("행의 갯수 : " , len(array))

[[0 1 2]
 [4 5 6]]
열의 갯수 :  3
행의 갯수 :  2


8. 넘파이를 사용하여 다음과 같은 행렬을 만든다
```
10 20 30 40
50 60 70 80
```

In [22]:
array = np.array([[10,20,30,40],[50,60,70,80]])
print(array)

[[10 20 30 40]
 [50 60 70 80]]


9. 넘파이를 사용하여 아래와 같은 행렬을 만든다.
    - 3*4 행렬 2개를 넣는다.
    - 각각의 행렬은 순서대로 아래의 값을 가짐.
      - 1~12
      - 11~22
    - 이후 행렬 각각의 행, 열, 깊이를 구할것

In [26]:
array = np.array([[[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]],
                  [[11,12,13,14],
                   [15,16,17,18],
                   [19,20,21,22]]])
print(array)
print("깊이 : ", len(array))
print("행 : ", len(array[0]))
print("열 : ", len(array[0][0]))


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
깊이 :  2
행 :  3
열 :  4
